extends RefCounted

class_name UIMetrics

const REFERENCE_VIEWPORT_SIZE := Vector2(1080.0, 1920.0)

const TOP_BAR_HEIGHT := 104.0
const BOTTOM_BAR_HEIGHT := 84.0
const TOP_BAR_PROFILE_SIZE := Vector2(76.0, 60.0)
const TOP_BAR_PROFILE_MARGIN := Vector2(12.0, 12.0)
const TOP_BAR_LEVEL_SIZE := Vector2(72.0, 20.0)
const TOP_BAR_LEVEL_MARGIN := Vector2(22.0, 76.0)
const CURRENCY_BOXES_SIZE := Vector2(144.0, 50.0)
const TOP_BAR_ROW_SEPARATION := 8
const TOP_BAR_ICON_SLOT_SIZE := Vector2(18.0, 18.0)

const COUNTER_MARGIN_LEFT := 12.0
const COUNTER_MARGIN_TOP := 116.0
const COUNTER_COLUMN_WIDTH := 112.0
const COUNTER_MARGIN_BOTTOM := 96.0
const COUNTER_LIST_SEPARATION := 8

const MENU_BACKGROUND_MARGIN := 14.0
const MENU_CONTENT_MARGIN := 28.0
const MENU_PANEL_SEPARATION := 12
const MENU_SECTION_LIST_SEPARATION := 12
const MENU_SECTION_BOX_SEPARATION := 6
const MENU_GRID_SPACING := 6
const MENU_SECTION_HEADER_FONT_SIZE := 16
const DUST_ACTION_ROW_SEPARATION := 12
const DUST_ACTION_PRIMARY_BUTTON_SIZE := Vector2(172.0, 48.0)
const DUST_ACTION_SECONDARY_BUTTON_SIZE := Vector2(82.0, 48.0)

const NAV_SLOTS_SIZE := Vector2(328.0, 56.0)
const NAV_SLOT_SIZE := Vector2(56.0, 56.0)
const NAV_SLOT_SEPARATION := 14
const SHOP_BUTTON_SIZE := Vector2(96.0, 96.0)
const SHOP_BUTTON_TOP_MARGIN := 136.0
const SHOP_BUTTON_RIGHT_MARGIN := 36.0
const FUSE_BUTTON_SIZE := Vector2(172.0, 172.0)

const WORLD_TITLE_TOP_MARGIN := 140.0
const WORLD_TITLE_HEIGHT := 36.0
const WORLD_PLANET_SIZE := Vector2(260.0, 260.0)
const WORLD_INFO_SIZE := Vector2(340.0, 92.0)
const WORLD_INFO_CENTER_OFFSET := Vector2(0.0, 194.0)
const WORLD_ACTION_STACK_SIZE := Vector2(264.0, 86.0)
const WORLD_ACTION_STACK_BOTTOM_MARGIN := 138.0
const WORLD_ACTION_STACK_SEPARATION := 8
const WORLD_WORKER_SLIDER_SIZE := Vector2(264.0, 24.0)
const WORLD_WORKER_BUTTON_SIZE := Vector2(192.0, 54.0)
const WORLD_PROGRESS_WIDTH := 144.0
const WORLD_PROGRESS_TOP_MARGIN := 116.0
const WORLD_PROGRESS_BOTTOM_MARGIN := 82.0
const WORLD_PROGRESS_STACK_SEPARATION := 12
const WORLD_PROGRESS_PANEL_PADDING := 8
const WORLD_PROGRESS_BAR_SIZE := Vector2(128.0, 16.0)
const WORLD_PARTICLE_SIZE := Vector2(3.0, 3.0)

const ERA_TIMELINE_MIN_HEIGHT := 360.0
const ERA_REQUIREMENT_MARGIN := 12
const ERA_REQUIREMENT_VBOX_SEPARATION := 8
const ERA_REQUIREMENT_LIST_SEPARATION := 4
const ERA_REQUIREMENT_CARD_SIDE_MARGIN := 8.0
const ERA_REQUIREMENT_CARD_TOP_RATIO := 0.80
const ERA_STATUS_FONT_SIZE := 16

const CURRENCY_DISPLAY_MIN_HEIGHT := 28.0
const CURRENCY_DISPLAY_FONT_SIZE := 14
const CURRENCY_PANEL_MARGIN_X := 8
const CURRENCY_PANEL_MARGIN_Y := 3

const ELEMENT_TILE_MIN_SIZE := 56.0
const ELEMENT_TILE_PADDING := 4
const ELEMENT_TILE_SEPARATION := 2
const ELEMENT_TILE_SYMBOL_MIN_HEIGHT := 18.0
const ELEMENT_TILE_AMOUNT_MIN_HEIGHT := 14.0
const ELEMENT_TILE_SYMBOL_FONT_SIZE := 14
const ELEMENT_TILE_AMOUNT_FONT_SIZE := 10

const UPGRADE_BUTTON_MIN_HEIGHT := 96.0
const UPGRADE_CONTENT_MARGIN_X := 12
const UPGRADE_CONTENT_MARGIN_Y := 8
const UPGRADE_CONTENT_SEPARATION := 10
const UPGRADE_INFO_SEPARATION := 2
const UPGRADE_COST_BUTTON_SIZE := Vector2(82.0, 48.0)
const UPGRADE_TITLE_FONT_SIZE := 16
const UPGRADE_BODY_FONT_SIZE := 12

const LABEL_FONT_SIZE_SMALL := 12
const LABEL_FONT_SIZE_MEDIUM := 14
const LABEL_FONT_SIZE_LARGE := 18
const LABEL_FONT_SIZE_XL := 26
