extends RefCounted

class_name UIMetrics

const REFERENCE_VIEWPORT_SIZE := Vector2(1080.0, 1920.0)
const FONT_SIZE_TITLE := 38
const FONT_SIZE_BODY := 26

const TOP_BAR_HEIGHT := 168.0
const BOTTOM_BAR_HEIGHT := 84.0
const TOP_BAR_PROFILE_SIZE := Vector2(TOP_BAR_HEIGHT, TOP_BAR_HEIGHT)
const TOP_BAR_PROFILE_MARGIN := Vector2.ZERO
const TOP_BAR_LEVEL_SIZE := Vector2(60.0, 26.0)
const TOP_BAR_LEVEL_INSET := Vector2(8.0, 8.0)
const CURRENCY_BOXES_SIZE := Vector2(320.0, 92.0)
const TOP_BAR_ROW_SEPARATION := 10
const TOP_BAR_ICON_SLOT_SIZE := Vector2(22.0, 22.0)

const COUNTER_MARGIN_LEFT := 12.0
const COUNTER_MARGIN_TOP := 180.0
const COUNTER_COLUMN_WIDTH := 168.0
const COUNTER_MARGIN_BOTTOM := 96.0
const COUNTER_LIST_SEPARATION := 10

const MENU_BACKGROUND_MARGIN := 14.0
const MENU_CONTENT_MARGIN := 28.0
const MENU_PANEL_SEPARATION := 18
const MENU_SECTION_LIST_SEPARATION := 18
const MENU_SECTION_BOX_SEPARATION := 10
const MENU_GRID_SPACING := 8
const MENU_GRID_SIDE_INSET := 32
const MENU_SECTION_HEADER_FONT_SIZE := FONT_SIZE_BODY
const MENU_BUTTON_MIN_HEIGHT := 68.0
const DUST_ACTION_ROW_SEPARATION := 16
const DUST_ACTION_PRIMARY_BUTTON_SIZE := Vector2(240.0, 72.0)
const DUST_ACTION_SECONDARY_BUTTON_SIZE := Vector2(140.0, 72.0)

const NAV_SLOTS_SIZE := Vector2(328.0, 56.0)
const NAV_SLOT_SIZE := Vector2(56.0, 56.0)
const NAV_SLOT_SEPARATION := 14
const SHOP_BUTTON_SIZE := Vector2(96.0, 96.0)
const SHOP_BUTTON_TOP_MARGIN := 188.0
const SHOP_BUTTON_RIGHT_MARGIN := 36.0
const FUSE_BUTTON_SIZE := Vector2(172.0, 172.0)

const WORLD_TITLE_TOP_MARGIN := 192.0
const WORLD_TITLE_HEIGHT := 52.0
const WORLD_PLANET_SIZE := Vector2(260.0, 260.0)
const WORLD_INFO_SIZE := Vector2(460.0, 220.0)
const WORLD_INFO_CENTER_OFFSET := Vector2(0.0, 248.0)
const WORLD_ACTION_STACK_SIZE := Vector2(320.0, 112.0)
const WORLD_ACTION_STACK_BOTTOM_MARGIN := 156.0
const WORLD_ACTION_STACK_SEPARATION := 8
const WORLD_WORKER_SLIDER_SIZE := Vector2(320.0, 24.0)
const WORLD_WORKER_BUTTON_SIZE := Vector2(240.0, 72.0)
const WORLD_PROGRESS_WIDTH := 220.0
const WORLD_PROGRESS_TOP_MARGIN := 188.0
const WORLD_PROGRESS_BOTTOM_MARGIN := 96.0
const WORLD_PROGRESS_STACK_SEPARATION := 16
const WORLD_PROGRESS_PANEL_PADDING := 12
const WORLD_PROGRESS_BAR_SIZE := Vector2(180.0, 20.0)
const WORLD_PARTICLE_SIZE := Vector2(3.0, 3.0)

const PLANETS_MENU_INFO_MIN_HEIGHT := 88.0
const PLANETS_MENU_TREE_MIN_HEIGHT := 780.0
const PLANETS_MENU_BOTTOM_HEIGHT := 540.0
const PLANETS_MENU_BOTTOM_SEPARATION := 12
const PLANETS_MENU_PANEL_RADIUS := 8
const PLANETS_MENU_PANEL_BORDER := 3
const PLANETS_MENU_PANEL_PADDING := 24
const PLANETS_MENU_TREE_PADDING := 24.0
const PLANETS_MENU_NODE_SMALL_SIZE := 24.0
const PLANETS_MENU_NODE_MEDIUM_SIZE := 36.0
const PLANETS_MENU_NODE_ROOT_SIZE := 60.0
const PLANETS_MENU_LINE_WIDTH := 6.0
const PLANETS_MENU_LINE_WIDTH_HIGHLIGHT := 9.0
const PLANETS_MENU_PLANET_PREVIEW_SIZE := Vector2(244.0, 244.0)
const PLANETS_MENU_RIGHT_BUTTON_SIZE := Vector2(240.0, 84.0)
const PLANETS_MENU_UPGRADE_ROW_MIN_HEIGHT := 78.0
const PLANETS_MENU_UPGRADE_ROW_SPACING := 12
const PLANETS_MENU_SECTION_HEADER_HEIGHT := 44.0

const ERA_TIMELINE_MIN_HEIGHT := 360.0
const ERA_REQUIREMENT_MARGIN := 18
const ERA_REQUIREMENT_VBOX_SEPARATION := 12
const ERA_REQUIREMENT_LIST_SEPARATION := 8
const ERA_REQUIREMENT_CARD_HEIGHT := 440.0
const ERA_REQUIREMENT_CARD_SIDE_MARGIN := 8.0
const ERA_REQUIREMENT_CARD_TOP_RATIO := 0.80
const ERA_STATUS_FONT_SIZE := FONT_SIZE_BODY

const CURRENCY_DISPLAY_MIN_HEIGHT := 40.0
const CURRENCY_DISPLAY_FONT_SIZE := 18
const CURRENCY_PANEL_MARGIN_X := 10
const CURRENCY_PANEL_MARGIN_Y := 5

const ELEMENT_TILE_MIN_SIZE := 56.0
const ELEMENT_TILE_PADDING := 4
const ELEMENT_TILE_SEPARATION := 2
const ELEMENT_TILE_SYMBOL_MIN_HEIGHT := 18.0
const ELEMENT_TILE_AMOUNT_MIN_HEIGHT := 32.0
const ELEMENT_TILE_SYMBOL_FONT_SIZE := 14
const ELEMENT_TILE_AMOUNT_FONT_SIZE := FONT_SIZE_BODY

const UPGRADE_BUTTON_MIN_HEIGHT := 220.0
const UPGRADE_CONTENT_MARGIN_X := 18
const UPGRADE_CONTENT_MARGIN_Y := 16
const UPGRADE_CONTENT_SEPARATION := 18
const UPGRADE_INFO_SEPARATION := 8
const UPGRADE_COST_BUTTON_SIZE := Vector2(156.0, 96.0)
const UPGRADE_TITLE_FONT_SIZE := FONT_SIZE_BODY
const UPGRADE_BODY_FONT_SIZE := FONT_SIZE_BODY

const LABEL_FONT_SIZE_SMALL := FONT_SIZE_BODY
const LABEL_FONT_SIZE_MEDIUM := FONT_SIZE_BODY
const LABEL_FONT_SIZE_LARGE := FONT_SIZE_BODY
const LABEL_FONT_SIZE_XL := FONT_SIZE_TITLE
